DROP TABLE IF EXISTS Terms;
DROP TABLE IF EXISTS Departments;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Teachers;
DROP TABLE IF EXISTS Buildings;
DROP TABLE IF EXISTS Rooms;
DROP TABLE IF EXISTS Classes;