DROP TABLE ClassRequirements;
DROP TABLE Classes;
DROP TABLE DegreeRequirements;
DROP TABLE Courses;
DROP TABLE Teachers;
DROP TABLE Degrees;
DROP TABLE Departments;
DROP TABLE Terms;
DROP TABLE Clubs;